[__config__]
oldver = 'old.json'
newver = 'new.json'
max_concurrency = 4
tries = 3

[GCC]
source = 'regex'
url = 'https://ftp.gnu.org/gnu/gcc/'
regex = 'gcc-([\d\.]+)\/'

[libiconv]
source = 'regex'
url = 'https://ftp.gnu.org/pub/gnu/libiconv/'
regex = 'libiconv-([\d\.]+)\.tar.gz'

[binutils]
source = 'regex'
url = 'https://ftp.gnu.org/gnu/binutils/'
regex = 'binutils-([\d\.]+)\.tar.bz2'

[gmp]
source = 'regex'
url = 'https://ftp.gnu.org/gnu/gmp/'
regex = 'gmp-([\d\.]+)\.tar.bz2'

[isl]
source = 'regex'
url = 'https://gcc.gnu.org/pub/gcc/infrastructure/'
regex = 'isl-([\d\.]+)\.tar.bz2'

[mpfr]
source = 'regex'
url = 'https://ftp.gnu.org/gnu/mpfr/'
regex = 'mpfr-([\d\.]+)\.tar.bz2'

[mpc]
source = 'regex'
url = 'https://ftp.gnu.org/gnu/mpc/'
regex = 'mpc-([\d\.]+)\.tar.gz'

[make]
source = 'regex'
url = 'https://ftp.gnu.org/pub/gnu/make/'
regex = 'make-([\d\.]+)\.tar.gz'

[cmake]
source = 'regex'
url = 'https://github.com/Kitware/CMake/tags'
regex = 'releases/tag/v([\d\.]+)"'

[ninja]
source = 'regex'
url = 'https://github.com/ninja-build/ninja//tags'
regex = 'releases/tag/v([\d\.]+)"'

[nasm]
source = 'regex'
url = 'https://github.com/netwide-assembler/nasm/tags'
regex = 'releases/tag/nasm-([\d\.]+)"'

[yasm]
source = 'regex'
url = 'https://github.com/yasm/yasm/tags'
regex = 'releases/tag/v([\d\.]+)"'

[pkgconf]
source = 'regex'
url = 'https://github.com/pkgconf/pkgconf/tags'
regex = 'releases/tag/pkgconf-([\d\.]+)"'

[LuaJIT]
source = 'regex'
url = 'https://github.com/LuaJIT/LuaJIT/tags'
regex = 'releases/tag/v([\w\.\-]+)'
from_pattern = '-'
to_pattern = '_'

[Mingw-w64-custom]
source = 'manual'
manual = '20230626_13.1.1_x64-ucrt_acc297ae58ccbcaa50c159a36572b408f6c7825c'

[Mingw-w64]
source = 'regex'
url = 'https://gcc-mcf.lhmouse.com/'
regex = 'mingw-w64-gcc-mcf_([\d]+_[\d\.]+_x64-ucrt_\w+)\.7z'

[nginx]
source = 'regex'
url = 'https://nginx.org/en/download.html'
regex = 'nginx-([\d\.]+)'

[openssl]
source = 'regex'
url = 'https://github.com/openssl/openssl/tags'
regex = 'releases/tag/openssl-([\d\.]+)"'

[Python]
source = 'regex'
url = 'https://www.python.org/downloads'
regex = 'Python (3.12[\d\.]*)'

[curl]
source = 'regex'
url = 'https://github.com/curl/curl/tags'
regex = 'releases/tag/curl-([\d\_]+)"'

# mpv
[amf]
source = 'regex'
url = 'https://github.com/GPUOpen-LibrariesAndSDKs/AMF/tags'
regex = 'releases/tag/v([\d\.]+)"'

[angle]
source = 'regex'
url = 'https://chromium.googlesource.com/angle/angle/+/refs/heads/main'
regex = 'ANGLE v([\d\.]+)'

[aom]
source = 'regex'
url = 'https://aomedia.googlesource.com/aom'
regex = 'v([\w\.-]+)'
from_pattern = '-'
to_pattern = '_'

[avisynth]
source = 'regex'
url = 'https://github.com/AviSynth/AviSynthPlus/tags'
regex = 'releases/tag/v([\d\.]+)"'

[brotli]
source = 'regex'
url = 'https://github.com/google/brotli/tags'
regex = 'releases/tag/v([\d\.]+)"'

[dav1d]
source = 'regex'
url = 'https://github.com/videolan/dav1d/tags'
regex = 'releases/tag/([\d\.]+)"'

[davs2]
source = 'regex'
url = 'https://github.com/pkuvcl/davs2/tags'
regex = 'releases/tag/([\d\.]+)"'

[ffmpeg]
source = 'regex'
url = 'https://ffmpeg.org/download.html'
regex = 'FFmpeg ([\d\.]+)'

[ffnvcodec]
source = 'regex'
url = 'https://github.com/FFmpeg/nv-codec-headers/tags'
regex = 'releases/tag/n([\d\.]+)"'

[freetype2]
source = 'regex'
url = 'https://github.com/freetype/freetype/tags'
regex = 'releases/tag/VER-([\d-]+)'
from_pattern = '-'
to_pattern = '_'

[fribidi]
source = 'regex'
url = 'https://github.com/fribidi/fribidi/tags'
regex = 'releases/tag/v([\d\.]+)"'

[harfbuzz]
source = 'regex'
url = 'https://github.com/harfbuzz/harfbuzz/tags'
regex = 'releases/tag/([\d\.]+)"'

[highway]
source = 'regex'
url = 'https://github.com/google/highway/tags'
regex = 'releases/tag/([\d\.]+)"'

[lame]
source = 'archpkg'
archpkg = 'lame'
strip_release = true

[lcms2]
source = 'archpkg'
archpkg = 'lcms2'
strip_release = true

[libaribb24]
source = 'regex'
url = 'https://github.com/nkoriyama/aribb24/tags'
regex = 'releases/tag/v([\d\.]+)"'

[libaribcaption]
source = 'regex'
url = 'https://github.com/xqq/libaribcaption/tags'
regex = 'releases/tag/v([\d\.]+)"'

[libass]
source = 'regex'
url = 'https://github.com/libass/libass/tags'
regex = 'releases/tag/([\d\.]+)"'

[libbluray]
source = 'archpkg'
archpkg = 'libbluray'
strip_release = true

[libbs2b]
source = 'regex'
url = 'http://bs2b.sourceforge.net/download.html'
regex = 'bs2b - ([\d\.]+)'

[libcaca]
source = 'regex'
url = 'https://github.com/cacalabs/libcaca/tags'
regex = 'releases/tag/v([\d\.]+\w+)"'

[libdovi]
source = 'regex'
url = 'https://github.com/quietvoid/dovi_tool/tags'
regex = 'libdovi-([\d\.]+)"'

[libdvdcss]
source = 'archpkg'
archpkg = 'libdvdcss'
strip_release = true

[libdvdnav]
source = 'archpkg'
archpkg = 'libdvdnav'
strip_release = true

[libdvdread]
source = 'archpkg'
archpkg = 'libdvdread'
strip_release = true

[libjpeg]
source = 'regex'
url = 'https://github.com/libjpeg-turbo/libjpeg-turbo/tags'
regex = 'releases/tag/([\d\.]+)"'

[libjxl]
source = 'regex'
url = 'https://github.com/libjxl/libjxl/tags'
regex = 'releases/tag/v([\d\.]+)"'

[libmodplug]
source = 'regex'
url = 'https://sourceforge.net/projects/modplug-xmms/files/libmodplug/'
regex = 'libmodplug-([\d\.]+)\.tar.gz'

[libmysofa]
source = 'regex'
url = 'https://github.com/hoene/libmysofa/tags'
regex = 'releases/tag/v([\d\.]+)"'

[libogg]
source = 'regex'
url = 'https://github.com/xiph/ogg/tags'
regex = 'releases/tag/v([\d\.]+)"'

[libopenmpt]
source = 'archpkg'
archpkg = 'libopenmpt'
strip_release = true

[libplacebo]
source = 'regex'
url = 'https://github.com/haasn/libplacebo/tags'
regex = 'releases/tag/v([\d\.]+)"'

[libpng]
source = 'regex'
url = 'https://github.com/glennrp/libpng/tags'
regex = 'releases/tag/v([\d\.]+)"'

[libsdl2]
source = 'regex'
url = 'https://github.com/libsdl-org/SDL/tags'
regex = 'releases/tag/release-([\d\.]+)"'

[libsixel]
source = 'regex'
url = 'https://github.com/libsixel/libsixel/tags'
regex = 'releases/tag/v([\d\.]+)"'

[libsoxr]
source = 'regex'
url = 'https://sourceforge.net/projects/soxr/files/'
regex = 'soxr-([\d\.]+)-Source\.tar.xz'

[libspeex]
source = 'regex'
url = 'https://gitlab.xiph.org/xiph/speex/-/tags'
regex = 'Speex-([\d\.]+)">'

[libsrt]
source = 'regex'
url = 'https://github.com/Haivision/srt/tags'
regex = 'releases/tag/v([\d\.]+)"'

[libssh]
source = 'regex'
url = 'https://gitlab.com/libssh/libssh-mirror/-/tags'
regex = 'libssh-([\d\.]+)">'

[libudfread]
source = 'regex'
url = 'https://code.videolan.org/videolan/libudfread/-/tags'
regex = '([\d\.]+) release'

[libunibreak]
source = 'regex'
url = 'https://github.com/adah1972/libunibreak/tags'
regex = 'releases/tag/libunibreak_([\d_]+)"'

[libvorbis]
source = 'archpkg'
archpkg = 'libvorbis'
strip_release = true

[libvpx]
source = 'regex'
url = 'https://chromium.googlesource.com/webm/libvpx'
regex = 'v([\d\.]+)"'

[libvpl]
source = 'regex'
url = 'https://github.com/oneapi-src/oneVPL/tags'
regex = 'releases/tag/v([\d\.]+)"'

[libwebp]
source = 'regex'
url = 'https://chromium.googlesource.com/webm/libwebp'
regex = 'v([\w\.-]+)'
from_pattern = '-'
to_pattern = '_'

[libxml2]
source = 'regex'
url = 'https://github.com/GNOME/libxml2/tags'
regex = 'releases/tag/v([\d\.]+)"'

[libxvid]
source = 'regex'
url = 'https://downloads.xvid.com/downloads/'
regex = 'xvidcore-([\d\.]+)\.tar.bz2'

[libzimg]
source = 'regex'
url = 'https://github.com/sekrit-twc/zimg/tags'
regex = 'releases/tag/release-([\d\.]+)"'

[libzvbi]
source = 'regex'
url = 'https://github.com/zapping-vbi/zvbi/tags'
regex = 'releases/tag/v([\d\.]+)"'

[luajit2]
source = 'regex'
url = 'https://github.com/openresty/luajit2/tags'
regex = 'releases/tag/v([\d\.]+-[\d]+)"'
from_pattern = '-'
to_pattern = '_'

[mbedtls]
source = 'regex'
url = 'https://github.com/Mbed-TLS/mbedtls/tags'
regex = 'releases/tag/v([\d\.]+)"'

[mpv]
source = 'regex'
url = 'https://github.com/mpv-player/mpv/tags'
regex = 'releases/tag/v([\d\.]+)"'

[mpv-git]
source = 'git'
git = 'https://github.com/mpv-player/mpv'
use_commit = true

[mujs]
source = 'regex'
url = 'https://github.com/ccxvii/mujs/tags'
regex = 'releases/tag/([\d\.]+)"'

[openal-soft]
source = 'regex'
url = 'https://github.com/kcat/openal-soft/tags'
regex = 'releases/tag/([\d\.]+)"'

[opus]
source = 'regex'
url = 'https://github.com/xiph/opus/tags'
regex = 'releases/tag/v([\d\.]+)"'

[rav1e]
source = 'github'
github = 'xiph/rav1e'
use_latest_release = true

[rubberband]
source = 'regex'
url = 'https://github.com/breakfastquay/rubberband/tags'
regex = 'releases/tag/v([\d\.]+)"'

[shaderc]
source = 'regex'
url = 'https://github.com/google/shaderc/tags'
regex = 'releases/tag/v([\d\.]+)"'

[spirv-cross]
source = 'regex'
url = 'https://github.com/KhronosGroup/SPIRV-Cross/tags'
regex = 'releases/tag/sdk-([\d\.]+)"'

[uavs3d]
source = 'regex'
url = 'https://github.com/uavs3/uavs3d/tags'
regex = 'releases/tag/v([\d\.]+)"'

[VapourSynth]
source = 'github'
github = 'vapoursynth/vapoursynth'
use_latest_release = true

[vulkan]
source = 'regex'
url = 'https://vulkan.lunarg.com/sdk/latest/windows.json'
regex = '([\d\.]+)'

[yt-dlp]
source = 'regex'
url = 'https://github.com/yt-dlp/yt-dlp/tags'
regex = 'releases/tag/([\d\.]+)"'

[xxhash]
source = 'regex'
url = 'https://github.com/Cyan4973/xxHash/tags'
regex = 'releases/tag/v([\d\.]+)"'

[zlib]
source = 'regex'
url = 'https://github.com/zlib-ng/zlib-ng/tags'
regex = 'releases/tag/([\d\.]+)"'
