[__config__]
oldver = 'old.json'
newver = 'new.json'
max_concurrency = 4

# toy
[Rust]
source = 'regex'
url = 'https://github.com/rust-lang/rust/tags'
regex = 'releases/tag/([\d\.]+)">'

[Python]
source = 'regex'
url = 'https://www.python.org/downloads'
regex = 'Python (3.9[\d\.]*)'

[VapourSynth]
source = 'github'
github = 'vapoursynth/vapoursynth'
use_latest_release = true

[LuaJIT]
source = 'regex'
url = 'https://luajit.org/download.html'
regex = 'LuaJIT-([\w\.-]+)'
from_pattern = '-'
to_pattern = '_'

[luajit2]
source = 'regex'
url = 'https://github.com/openresty/luajit2/tags'
regex = 'v([\d\.]+-[\d]+)'
from_pattern = '-'
to_pattern = '_'

[GCC]
source = 'regex'
url = 'https://gcc.gnu.org'
regex = '>GCC ([\d\.]+)<'

[Mingw-w64]
source = 'manual'
manual = '20220429_12.0.1_x64-ucrt_13f0746dd680e1df89ab23a964c7b8ade13bb59f'

[Mingw-w64-real]
source = 'regex'
url = 'https://gcc-mcf.lhmouse.com/'
regex = 'mingw-w64-gcc-mcf_([\d]+_[\d\.]+_x64-ucrt_\w+)\.7z'

# nginx
[nginx]
source = 'regex'
url = 'https://nginx.org/en/download.html'
regex = 'nginx-([\d\.]+)'

[zlib]
source = 'regex'
url = 'https://github.com/madler/zlib/tags'
regex = 'releases/tag/v([\d\.]+)">'

[openssl]
source = 'regex'
url = 'https://github.com/openssl/openssl/tags'
regex = 'releases/tag/OpenSSL_([\d_]+[a-z])">'

# mpv
[ffmpeg]
source = 'regex'
url = 'https://ffmpeg.org/download.html'
regex = 'FFmpeg ([\d\.]+)'

[mpv]
source = 'regex'
url = 'https://github.com/mpv-player/mpv/tags'
regex = 'releases/tag/v([\d\.]+)">'

[brotli]
source = 'regex'
url = 'https://github.com/google/brotli/tags'
regex = 'releases/tag/v([\d\.]+)">'

[dav1d]
source = 'regex'
url = 'https://github.com/videolan/dav1d/tags'
regex = 'releases/tag/([\d\.]+)">'

[ffnvcodec]
source = 'regex'
url = 'https://github.com/FFmpeg/nv-codec-headers/tags'
regex = 'releases/tag/n([\d\.]+)">'

[highway]
source = 'regex'
url = 'https://github.com/google/highway/tags'
regex = 'releases/tag/([\d\.]+)">'

[lame]
source = 'archpkg'
archpkg = 'lame'
strip_release = true

[libogg]
source = 'archpkg'
archpkg = 'libogg'
strip_release = true

[libsdl2]
source = 'regex'
url = 'https://github.com/libsdl-org/SDL/tags'
regex = 'releases/tag/release-([\d\.]+)">'

[openal-soft]
source = 'regex'
url = 'https://github.com/kcat/openal-soft/tags'
regex = 'releases/tag/([\d\.]+)">'

[libvorbis]
source = 'archpkg'
archpkg = 'libvorbis'
strip_release = true

[opus]
source = 'archpkg'
archpkg = 'opus'
strip_release = true

[lcms2]
source = 'archpkg'
archpkg = 'lcms2'
strip_release = true

[libass]
source = 'regex'
url = 'https://github.com/libass/libass/tags'
regex = 'releases/tag/([\d\.]+)">'

[freetype2]
source = 'regex'
url = 'https://download.savannah.gnu.org/releases/freetype'
regex = 'freetype-([\d\.]+)\.tar'

[fribidi]
source = 'regex'
url = 'https://github.com/fribidi/fribidi/tags'
regex = 'releases/tag/v([\d\.]+)">'

[harfbuzz]
source = 'regex'
url = 'https://github.com/harfbuzz/harfbuzz/tags'
regex = 'releases/tag/([\d\.]+)">'

[libbluray]
source = 'archpkg'
archpkg = 'libbluray'
strip_release = true

[libdvdnav]
source = 'archpkg'
archpkg = 'libdvdnav'
strip_release = true

[libdvdread]
source = 'archpkg'
archpkg = 'libdvdread'
strip_release = true

[libdvdcss]
source = 'archpkg'
archpkg = 'libdvdcss'
strip_release = true

[vulkan]
source = 'regex'
url = 'https://github.com/KhronosGroup/Vulkan-Loader/tags'
regex = 'releases/tag/v([\d\.]+)">'

[spirv-cross]
source = 'regex'
url = 'https://github.com/KhronosGroup/SPIRV-Cross/tags'
regex = 'releases/tag/([\d-]+)">'
from_pattern = '-'
to_pattern = '.'

[shaderc]
source = 'regex'
url = 'https://github.com/google/shaderc/tags'
regex = 'releases/tag/v([\d\.]+)">'

[libepoxy]
source = 'regex'
url = 'https://github.com/anholt/libepoxy/tags'
regex = 'releases/tag/([\d\.]+)">'

[libplacebo]
source = 'regex'
url = 'https://github.com/haasn/libplacebo/tags'
regex = 'releases/tag/v([\d\.]+)">'

# image
[libpng]
source = 'regex'
url = 'https://github.com/glennrp/libpng/tags'
regex = 'releases/tag/v([\d\.]+)">'

[libjpeg]
source = 'regex'
url = 'https://github.com/libjpeg-turbo/libjpeg-turbo/tags'
regex = 'releases/tag/([\d\.]+)">'

[libjxl]
source = 'regex'
url = 'https://github.com/libjxl/libjxl/tags'
regex = 'releases/tag/v([\d\.]+)">'

# leech
[aria2]
source = 'github'
github = 'aria2/aria2'
