[__config__]
oldver = 'old.json'
newver = 'new.json'
max_concurrency = 4

[Python]
source = 'regex'
url = 'https://www.python.org/downloads'
regex = 'Python (3.10[\d\.]*)'

[VapourSynth]
source = 'github'
github = 'vapoursynth/vapoursynth'
use_latest_release = true

[LuaJIT]
source = 'regex'
url = 'https://luajit.org/download.html'
regex = 'LuaJIT-([\w\.-]+)'
from_pattern = '-'
to_pattern = '_'

[luajit2]
source = 'regex'
url = 'https://github.com/openresty/luajit2/tags'
regex = 'v([\d\.]+-[\d]+)'
from_pattern = '-'
to_pattern = '_'

[GCC]
source = 'regex'
url = 'https://gcc.gnu.org'
regex = '>GCC ([\d\.]+)<'

[Mingw-w64]
source = 'manual'
manual = '20220707_12.1.1_x64-ucrt_d847d702d627c147cbe2329d50cf5ed5bccc06ab'

[Mingw-w64-real]
source = 'regex'
url = 'https://gcc-mcf.lhmouse.com/'
regex = 'mingw-w64-gcc-mcf_([\d]+_[\d\.]+_x64-ucrt_\w+)\.7z'

# nginx
[nginx]
source = 'regex'
url = 'https://nginx.org/en/download.html'
regex = 'nginx-([\d\.]+)'

[zlib]
source = 'regex'
url = 'https://github.com/madler/zlib/tags'
regex = 'releases/tag/v([\d\.]+)">'

[openssl]
source = 'regex'
url = 'https://github.com/openssl/openssl/tags'
regex = 'releases/tag/OpenSSL_([\d_]+[a-z])">'

# mpv
[ffmpeg]
source = 'regex'
url = 'https://ffmpeg.org/download.html'
regex = 'FFmpeg ([\d\.]+)'

[mpv]
source = 'regex'
url = 'https://github.com/mpv-player/mpv/tags'
regex = 'releases/tag/v([\d\.]+)">'

[brotli]
source = 'regex'
url = 'https://github.com/google/brotli/tags'
regex = 'releases/tag/v([\d\.]+)">'

[dav1d]
source = 'regex'
url = 'https://github.com/videolan/dav1d/tags'
regex = 'releases/tag/([\d\.]+)">'

[ffnvcodec]
source = 'regex'
url = 'https://github.com/FFmpeg/nv-codec-headers/tags'
regex = 'releases/tag/n([\d\.]+)">'

[highway]
source = 'regex'
url = 'https://github.com/google/highway/tags'
regex = 'releases/tag/([\d\.]+)">'

[lame]
source = 'archpkg'
archpkg = 'lame'
strip_release = true

[libbs2b]
source = 'regex'
url = 'http://bs2b.sourceforge.net/download.html'
regex = 'bs2b - ([\d\.]+)'

[libmfx]
source = 'regex'
url = 'https://github.com/lu-zero/mfx_dispatch/tags'
regex = 'releases/tag/([\d\.]+)">'

[libmodplug]
source = 'regex'
url = 'https://sourceforge.net/projects/modplug-xmms/files/libmodplug/'
regex = 'libmodplug-([\d\.]+)\.tar.gz'

[libmysofa]
source = 'regex'
url = 'https://github.com/hoene/libmysofa/tags'
regex = 'releases/tag/v([\d\.]+)">'

[libopenmpt]
source = 'regex'
url = 'https://lib.openmpt.org/libopenmpt/'
regex = 'libopenmpt release ([\d\.]+)'

[libogg]
source = 'archpkg'
archpkg = 'libogg'
strip_release = true

[libsdl2]
source = 'regex'
url = 'https://github.com/libsdl-org/SDL/tags'
regex = 'releases/tag/release-([\d\.]+)">'

[libspeex]
source = 'regex'
url = 'https://gitlab.xiph.org/xiph/speex/-/tags'
regex = 'Speex-([\d\.]+)">'

[libvpx]
source = 'regex'
url = 'https://chromium.googlesource.com/webm/libvpx/+/refs/tags'
regex = 'v([\d\.]+)">'

[libxml2]
source = 'regex'
url = 'https://gitlab.gnome.org/GNOME/libxml2/-/tags'
regex = 'v([\d\.]+)">'

[openal-soft]
source = 'regex'
url = 'https://github.com/kcat/openal-soft/tags'
regex = 'releases/tag/([\d\.]+)">'

[libvorbis]
source = 'archpkg'
archpkg = 'libvorbis'
strip_release = true

[opus]
source = 'archpkg'
archpkg = 'opus'
strip_release = true

[lcms2]
source = 'archpkg'
archpkg = 'lcms2'
strip_release = true

[libass]
source = 'regex'
url = 'https://github.com/libass/libass/tags'
regex = 'releases/tag/([\d\.]+)">'

[freetype2]
source = 'regex'
url = 'https://github.com/freetype/freetype/tags'
regex = 'VER-([\d-]+)'
from_pattern = '-'
to_pattern = '_'

[fribidi]
source = 'regex'
url = 'https://github.com/fribidi/fribidi/tags'
regex = 'releases/tag/v([\d\.]+)">'

[harfbuzz]
source = 'regex'
url = 'https://github.com/harfbuzz/harfbuzz/tags'
regex = 'releases/tag/([\d\.]+)">'

[libbluray]
source = 'archpkg'
archpkg = 'libbluray'
strip_release = true

[libudfread]
source = 'archpkg'
archpkg = 'libudfread'
strip_release = true

[libdvdnav]
source = 'archpkg'
archpkg = 'libdvdnav'
strip_release = true

[libdvdread]
source = 'archpkg'
archpkg = 'libdvdread'
strip_release = true

[libdvdcss]
source = 'archpkg'
archpkg = 'libdvdcss'
strip_release = true

[libxvid]
source = 'regex'
url = 'https://downloads.xvid.com/downloads/'
regex = 'xvidcore-([\d\.]+)\.tar.bz2'

[libzimg]
source = 'regex'
url = 'https://github.com/sekrit-twc/zimg/tags'
regex = 'release-([\d\.]+)">'

[mbedtls]
source = 'regex'
url = 'https://github.com/Mbed-TLS/mbedtls/tags'
regex = 'v([\d\.]+)">'

[mujs]
source = 'regex'
url = 'https://github.com/ccxvii/mujs/tags'
regex = 'releases/tag/([\d\.]+)">'

[rubberband]
source = 'regex'
url = 'https://github.com/breakfastquay/rubberband/tags'
regex = 'releases/tag/v([\d\.]+)">'

[spirv-cross]
source = 'regex'
url = 'https://github.com/KhronosGroup/SPIRV-Cross/tags'
regex = 'releases/tag/([\d-]+)">'
from_pattern = '-'
to_pattern = '.'

[shaderc]
source = 'regex'
url = 'https://github.com/google/shaderc/tags'
regex = 'releases/tag/v([\d\.]+)">'

[vulkan]
source = 'regex'
url = 'https://github.com/KhronosGroup/Vulkan-Loader/tags'
regex = 'releases/tag/v([\d\.]+)">'

[libcaca]
source = 'regex'
url = 'https://github.com/cacalabs/libcaca/tags'
regex = 'v([\d\.]+\w+)">'

[libepoxy]
source = 'regex'
url = 'https://github.com/anholt/libepoxy/tags'
regex = 'releases/tag/([\d\.]+)">'

[libplacebo]
source = 'regex'
url = 'https://github.com/haasn/libplacebo/tags'
regex = 'releases/tag/v([\d\.]+)">'

# image
[libpng]
source = 'regex'
url = 'https://github.com/glennrp/libpng/tags'
regex = 'releases/tag/v([\d\.]+)">'

[libjpeg]
source = 'regex'
url = 'https://github.com/libjpeg-turbo/libjpeg-turbo/tags'
regex = 'releases/tag/([\d\.]+)">'

[libjxl]
source = 'regex'
url = 'https://github.com/libjxl/libjxl/tags'
regex = 'releases/tag/v([\d\.]+)">'

[libwebp]
source = 'regex'
url = 'https://chromium.googlesource.com/webm/libwebp'
regex = 'v([\d\.]+)'
