[__config__]
oldver = 'old.json'
newver = 'new.json'
max_concurrency = 4
tries = 2

[GCC]
source = 'regex'
url = 'https://gcc.gnu.org'
regex = '>GCC ([\d\.]+)<'

[LuaJIT]
source = 'regex'
url = 'https://luajit.org/download.html'
regex = 'LuaJIT-([\w\.-]+)'
from_pattern = '-'
to_pattern = '_'

[luajit2]
source = 'regex'
url = 'https://github.com/openresty/luajit2/tags'
regex = 'releases/tag/v([\d\.]+-[\d]+)"'
from_pattern = '-'
to_pattern = '_'

[Mingw-w64]
source = 'manual'
manual = '20221004_12.2.1_x64-ucrt_5a374059e9f3d0c25c31d841199d7c110a4e0b87'

[Mingw-w64-real]
source = 'regex'
url = 'https://gcc-mcf.lhmouse.com/'
regex = 'mingw-w64-gcc-mcf_([\d]+_[\d\.]+_x64-ucrt_\w+)\.7z'

[Python]
source = 'regex'
url = 'https://www.python.org/downloads'
regex = 'Python (3.10[\d\.]*)'

[VapourSynth]
source = 'github'
github = 'vapoursynth/vapoursynth'
use_latest_release = true

[nginx]
source = 'regex'
url = 'https://nginx.org/en/download.html'
regex = 'nginx-([\d\.]+)'

[openssl]
source = 'regex'
url = 'https://github.com/openssl/openssl/tags'
regex = 'releases/tag/OpenSSL_([\d_]+[a-z])"'

# mpv
[amf]
source = 'regex'
url = 'https://github.com/GPUOpen-LibrariesAndSDKs/AMF/tags'
regex = 'releases/tag/v([\d\.]+)"'

[angle]
source = 'regex'
url = 'https://chromium.googlesource.com/angle/angle/+/refs/heads/main'
regex = 'ANGLE v([\d\.]+)'

[avisynth]
source = 'regex'
url = 'https://github.com/AviSynth/AviSynthPlus/tags'
regex = 'releases/tag/v([\d\.]+)"'

[brotli]
source = 'regex'
url = 'https://github.com/google/brotli/tags'
regex = 'releases/tag/v([\d\.]+)"'

[dav1d]
source = 'regex'
url = 'https://github.com/videolan/dav1d/tags'
regex = 'releases/tag/([\d\.]+)"'

[ffmpeg]
source = 'regex'
url = 'https://ffmpeg.org/download.html'
regex = 'FFmpeg ([\d\.]+)'

[ffmpeg-git]
source = 'git'
git = 'https://github.com/FFmpeg/FFmpeg'
use_commit = true

[ffnvcodec]
source = 'regex'
url = 'https://github.com/FFmpeg/nv-codec-headers/tags'
regex = 'releases/tag/n([\d\.]+)"'

[freetype2]
source = 'regex'
url = 'https://github.com/freetype/freetype/tags'
regex = 'releases/tag/VER-([\d-]+)'
from_pattern = '-'
to_pattern = '_'

[fribidi]
source = 'regex'
url = 'https://github.com/fribidi/fribidi/tags'
regex = 'releases/tag/v([\d\.]+)"'

[harfbuzz]
source = 'regex'
url = 'https://github.com/harfbuzz/harfbuzz/tags'
regex = 'releases/tag/([\d\.]+)"'

[highway]
source = 'regex'
url = 'https://github.com/google/highway/tags'
regex = 'releases/tag/([\d\.]+)"'

[lame]
source = 'archpkg'
archpkg = 'lame'
strip_release = true

[lcms2]
source = 'archpkg'
archpkg = 'lcms2'
strip_release = true

[libass]
source = 'regex'
url = 'https://github.com/libass/libass/tags'
regex = 'releases/tag/([\d\.]+)"'

[libbluray]
source = 'archpkg'
archpkg = 'libbluray'
strip_release = true

[libbs2b]
source = 'regex'
url = 'http://bs2b.sourceforge.net/download.html'
regex = 'bs2b - ([\d\.]+)'

[libcaca]
source = 'regex'
url = 'https://github.com/cacalabs/libcaca/tags'
regex = 'releases/tag/v([\d\.]+\w+)"'

[libdvdcss]
source = 'archpkg'
archpkg = 'libdvdcss'
strip_release = true

[libdvdnav]
source = 'archpkg'
archpkg = 'libdvdnav'
strip_release = true

[libdvdread]
source = 'archpkg'
archpkg = 'libdvdread'
strip_release = true

[libiconv]
source = 'regex'
url = 'https://ftp.gnu.org/pub/gnu/libiconv/'
regex = 'libiconv-([\d\.]+)\.tar.gz'

[libjpeg]
source = 'regex'
url = 'https://github.com/libjpeg-turbo/libjpeg-turbo/tags'
regex = 'releases/tag/([\d\.]+)"'

[libjxl]
source = 'regex'
url = 'https://github.com/libjxl/libjxl/tags'
regex = 'releases/tag/v([\d\.]+)"'

[libmfx]
source = 'regex'
url = 'https://github.com/lu-zero/mfx_dispatch/tags'
regex = 'releases/tag/([\d\.]+)"'

[libmodplug]
source = 'regex'
url = 'https://sourceforge.net/projects/modplug-xmms/files/libmodplug/'
regex = 'libmodplug-([\d\.]+)\.tar.gz'

[libmysofa]
source = 'regex'
url = 'https://github.com/hoene/libmysofa/tags'
regex = 'releases/tag/v([\d\.]+)"'

[libogg]
source = 'archpkg'
archpkg = 'libogg'
strip_release = true

[libopenmpt]
source = 'archpkg'
archpkg = 'libopenmpt'
strip_release = true

[libplacebo]
source = 'regex'
url = 'https://github.com/haasn/libplacebo/tags'
regex = 'releases/tag/v([\d\.]+)"'

[libpng]
source = 'regex'
url = 'https://github.com/glennrp/libpng/tags'
regex = 'releases/tag/v([\d\.]+)"'

[libsdl2]
source = 'regex'
url = 'https://github.com/libsdl-org/SDL/tags'
regex = 'releases/tag/release-([\d\.]+)"'

[libsixel]
source = 'regex'
url = 'https://github.com/libsixel/libsixel/tags'
regex = 'releases/tag/v([\d\.]+)"'

[libsoxr]
source = 'regex'
url = 'https://sourceforge.net/projects/soxr/files/'
regex = 'soxr-([\d\.]+)-Source\.tar.xz'

[libspeex]
source = 'regex'
url = 'https://gitlab.xiph.org/xiph/speex/-/tags'
regex = 'Speex-([\d\.]+)">'

[libsrt]
source = 'regex'
url = 'https://github.com/Haivision/srt/tags'
regex = 'releases/tag/v([\d\.]+)"'

[libssh]
source = 'regex'
url = 'https://git.libssh.org/projects/libssh.git/'
regex = 'libssh-([\d\.]+)\.tar.xz'

[libudfread]
source = 'manual'
manual = '1.1.2'

[libvorbis]
source = 'archpkg'
archpkg = 'libvorbis'
strip_release = true

[libvpx]
source = 'regex'
url = 'https://chromium.googlesource.com/webm/libvpx'
regex = 'v([\d\.]+)">'

[libwebp]
source = 'regex'
url = 'https://chromium.googlesource.com/webm/libwebp'
regex = 'v([\d\.]+)'

[libxml2]
source = 'regex'
url = 'https://gitlab.gnome.org/GNOME/libxml2/-/tags'
regex = 'v([\d\.]+)"'

[libxvid]
source = 'regex'
url = 'https://downloads.xvid.com/downloads/'
regex = 'xvidcore-([\d\.]+)\.tar.bz2'

[libzimg]
source = 'regex'
url = 'https://github.com/sekrit-twc/zimg/tags'
regex = 'releases/tag/release-([\d\.]+)"'

[mbedtls]
source = 'regex'
url = 'https://github.com/Mbed-TLS/mbedtls/tags'
regex = 'releases/tag/v([\d\.]+)"'

[mpv]
source = 'regex'
url = 'https://github.com/mpv-player/mpv/tags'
regex = 'releases/tag/v([\d\.]+)"'

[mpv-git]
source = 'git'
git = 'https://github.com/mpv-player/mpv'
use_commit = true

[mujs]
source = 'regex'
url = 'https://github.com/ccxvii/mujs/tags'
regex = 'releases/tag/([\d\.]+)"'

[openal-soft]
source = 'regex'
url = 'https://github.com/kcat/openal-soft/tags'
regex = 'releases/tag/([\d\.]+)"'

[opus]
source = 'regex'
url = 'https://github.com/xiph/opus/tags'
regex = 'releases/tag/v([\d\.]+)"'

[rubberband]
source = 'regex'
url = 'https://github.com/breakfastquay/rubberband/tags'
regex = 'releases/tag/v([\d\.]+)"'

[shaderc]
source = 'regex'
url = 'https://github.com/google/shaderc/tags'
regex = 'releases/tag/v([\d\.]+)"'

[spirv-cross]
source = 'regex'
url = 'https://github.com/KhronosGroup/SPIRV-Cross/tags'
regex = 'releases/tag/([\d-]+)"'
from_pattern = '-'
to_pattern = '.'

[vulkan]
source = 'regex'
url = 'https://github.com/KhronosGroup/Vulkan-Loader/tags'
regex = 'releases/tag/sdk-([\d\.]+)"'

[yt-dlp]
source = 'regex'
url = 'https://github.com/yt-dlp/yt-dlp/tags'
regex = 'releases/tag/([\d\.]+)"'

[zlib]
source = 'regex'
url = 'https://github.com/madler/zlib/tags'
regex = 'releases/tag/v([\d\.]+)"'
