name: leech

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        url:
        - https://mega.nz/file/wbBTmKIB#vkhhniVxYtl47wLzcc1mF2kXs6aIMJ8vD5juY89F_iE
        - https://mega.nz/file/5OBRVCLQ#2SI9djqBxrL3I6Ijnev9YRSIVZcRIT23VkwF1zQJ7R4
        - https://mega.nz/file/saIXDCZb#dzrm4TF7vDNQ5tFO_rzPDLZx2QB4JKGtpDjKEVO6VFo
        - https://mega.nz/file/VLIBjIzT#jL-RSaRGXqqVDWJQyorbdx_jME2uRpnOBedlnqFZM7g
        - https://mega.nz/file/tHYxRKpC#Z7d4jLKefppFNzonNQutM6_yBGsFk4ZACO0h-Wx0n-Y
        - https://mega.nz/file/pHQTFIaD#7ls3kCjDMuFkeKQrjzo9tf4A5xVU82rMJXDZDL1oFVU
        - https://mega.nz/file/BfY1GIiJ#ZcuAeHMTgTEIpESlxe9eKV1AtiE9yIaEb28biZ7uqOs
        - https://mega.nz/file/gbBFzIyB#akHFD7uALaMKgKxXuDngKPnI_rfKlS3kkwq-pkApyXU
        - https://mega.nz/file/cGQVFKjI#kEoFuUQfcXP0Q9SsdtGXk2oeGK2hpn1gy8ULVX4A3PI
        - https://mega.nz/file/VDYjGaAR#BhJsf5TF4dcKYDUa1B1SVHWTOlFsR5fx7D6tcUAhrBE
        - https://mega.nz/file/RTQFTADL#f_8oV4hbuLNdQWe_uPCqjFkuWlOpQDrDYAt9keYSTnM
        - https://mega.nz/file/gLBhmYab#eQ-QHm6Gg-k8OcNZuT9ZuptfH8RvEmyepJp53em_lF8
        - https://mega.nz/file/tfBVgCBS#6UiEXNtykEUo6fLnIDP2Q_qYHlRyHKi4uztTR0284aA
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
      id: cache
      with:
        path: megatools-1.11.0-git-20200830-linux-x86_64
        key: megatools-1.11.0-git-20200830-linux-x86_64
    - name: Mega
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl -OL https://megatools.megous.com/builds/experimental/megatools-1.11.0-git-20200830-linux-x86_64.tar.gz
        tar xvf *.gz
    - name: Leech
      run: |
        mkdir leech
        megatools*/megatools dl --path leech/ ${{ matrix.url }}
        cd leech
        find . -size +2G -exec split -b 1G --numeric-suffixes=1 {} {}.0 \;
        find . -size +2G -exec rm {} \;
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: leech/*
        tag: latest
        overwrite: true
        file_glob: true
