name: leech

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        url:
        - https://mega.nz/file/VR90VQ4T#zh0R7Z8zjCwYgqq0KWicohrQHHXW2MkJjrCYlbICD84
        - https://mega.nz/file/kR9GzJhK#3X6cXW8mJe1LNFWAfXz71sHwS3VaVvp5hzS_q54iG20
        - https://mega.nz/file/XhIg2TDa#RJOyOboT7gT4ZDZHCJYejpm8b0_TTPIZ8rxxvSSNvG0
        - https://mega.nz/file/xIsyxAQb#EBxDEBmW9ZQWw34S6l_mDuFErjNYza2whJyOOqTaYvc
        - https://mega.nz/file/xYlWDKxR#GMAfhJNjyK2-E416YhPXKCGMIW_vBaLgb-knu7EGl-Q
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
      id: cache
      with:
        path: megatools-1.11.0-git-20200830-linux-x86_64
        key: megatools-1.11.0-git-20200830-linux-x86_64
    - name: Mega
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl -OL https://megatools.megous.com/builds/experimental/megatools-1.11.0-git-20200830-linux-x86_64.tar.gz
        tar xvf *.gz
    - name: Leech
      run: |
        mkdir leech
        megatools*/megatools dl --path leech/ ${{ matrix.url }}
        cd leech
        find . -size +2G -exec split -b 1G --numeric-suffixes=1 {} {}.0 \;
        find . -size +2G -exec rm {} \;
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: leech/*
        tag: latest
        overwrite: true
        file_glob: true
