name: leech

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        url:
        - https://mega.nz/folder/xXpTzI5T#gOPIKjEIwuD8Bxm-quzOKQ/file/sGwGyBbS
        - https://mega.nz/folder/xXpTzI5T#gOPIKjEIwuD8Bxm-quzOKQ/file/NXQW1RjI
        - https://mega.nz/folder/xXpTzI5T#gOPIKjEIwuD8Bxm-quzOKQ/file/kDYHkA5T
        - https://mega.nz/folder/xXpTzI5T#gOPIKjEIwuD8Bxm-quzOKQ/file/dGIWkBAb
        - https://mega.nz/folder/xXpTzI5T#gOPIKjEIwuD8Bxm-quzOKQ/file/kHASFDKD
        - https://mega.nz/folder/xXpTzI5T#gOPIKjEIwuD8Bxm-quzOKQ/file/hP4kyCyI
        - https://mega.nz/folder/xXpTzI5T#gOPIKjEIwuD8Bxm-quzOKQ/file/ROg2DIxQ
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
      id: cache
      with:
        path: megatools-1.11.0-git-20210505-linux-x86_64
        key: megatools-1.11.0-git-20210505-linux-x86_64
    - name: Mega
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl -OL https://megatools.megous.com/builds/experimental/megatools-1.11.0-git-20210505-linux-x86_64.tar.gz
        tar xvf *.gz
    - name: Leech
      run: |
        mkdir leech
        megatools*/megatools dl --path leech/ ${{ matrix.url }}
        cd leech
        find . -size +2G -exec split -b 1G --numeric-suffixes=1 {} {}.0 \;
        find . -size +2G -exec rm {} \;
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: leech/*
        tag: latest
        overwrite: true
        file_glob: true
