name: leech

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        url:
        - https://mega.nz/file/250G2TxQ#ua7tv3u5f5Nct7LkTwz_NLqWeIJTE7JZm3rhoXGgHyo
        - https://mega.nz/file/fxkUjQKJ#O9Op540klJkfbmI8hTUiI4x7s--8ZxdmcRQbqAg_9_I
        - https://mega.nz/file/S89jlCKD#8ETYXuuQcdRhULz0hR9GkeXARUbgYqMreMBf_DrXaWI
        - https://mega.nz/file/3x1glQZB#QWHkqc92wAMF_PVUC1H_oreZbvaPYzrwdRbgwNRrnhQ
        - https://mega.nz/file/NVN2VZrD#NHprkEQUp7d5ZVn5DEKX17RqYSH2eEcidt7ht6X_Jbg
        - https://mega.nz/file/pQVEWbJQ#-Dk3D3RrZ1Q4y3wM7LNngmHyGX0ZbZj6EJLydEK-8wQ
        - https://mega.nz/file/4JFU2bpS#5eGNEyeka1591Uu6XqZ7rumhSd_O5GgoX5RK_2yxA14
        - https://mega.nz/file/8QEEjZTS#O8gORQuo-F_01IDfj9HQ7vFHAJ5iziaZfh9AKuInEqM
        - https://mega.nz/file/C89AHSJR#ig-O5HezTYboHD5RktpdGdCTSf7A-d9eDRUkj3Cuohc
        - https://mega.nz/file/Ot9g2SaK#ffjMv1ZZQ-L-jaDpZf3Xpeus73ygNjBaaaX7jIhaOVM
        - https://mega.nz/file/Sx90kIAb#TdeMHmLv5JX0bH63nCRzDoZCBYdlSJISKfINAQK4vX0
        - https://mega.nz/file/4bw0hCZZ#dQlUSxcf0kqIwREFXeDK-MJV5OorV7ypw19N3sHTCw4
        - https://mega.nz/file/UKxiBY6A#NaIQqyZRB9o2VnQemnh6lyunz-wpgTs1gzqDa48zw_E
        - https://mega.nz/file/EEp0kYLJ#4zVuplpXu8Qbcbw-ZOE0m8PlyhiJUfURzASnOL-Y3pw
        - https://mega.nz/file/IZpWESoA#3bLi4Vkc9rAYHAEWIdmXbvG4sF-3Hbc_38kDMo6wfGI
        - https://mega.nz/file/EZ50nAhJ#bkI9NxwvQRgiC8FuBrd1MYLkc4bPjgKzwkB60GOpDuw
        - https://mega.nz/file/tRoykYxI#fQf2sbbRz5aawmJU0GanA7271a0pvQCzvAM_G5ahpKI
        - https://mega.nz/file/oR4kzSoK#2-hQzaVaiylsxf4D4ZOy1g8qWQ_evr9Ugo4JaKB52k0
        - https://mega.nz/file/ropwhDxZ#MyTnEWN-HD5UDb6bjO_gL3BiiBZ4GBSn9Bjr3-1Uy4k
        - https://mega.nz/file/UIV2STRT#PTZKWJ6hHnbgUc0I0Ycd9j3K7pgAaWHb9ailKzgQxcg
        - https://mega.nz/file/8IdyHT4S#gNk1izLiyR2E1TerJfMGsV6YOF0yTTK2h8vTh8ayakQ
        - https://mega.nz/file/r9Y11IgQ#hIdZLJvmSl07u0WuO4HcUHF7hCsrWvfI8C9Nkh6ZAOY
        - https://mega.nz/file/Wg8w1aDS#bqP12Cm-J3w7ADr_S-x-Ka74482e658XWZ5Hr9z_I8c
        - https://mega.nz/file/K4tygApC#NcyqTUJ46ItqSVDWGSFU-vQ5sIuiyu70ubARhVTs9Ew
        - https://mega.nz/file/Gw1iXCTa#O5IdEuc73A65_QoZj2W3ySX2HkSexoV08l2Ei9MFPbU
        - https://mega.nz/file/bx0knSRS#1jlnQ7LP9LBUNa4E93xYlHkXZ0quP-K-_uEhix1tRzg
        - https://mega.nz/file/G8JwURrA#E9vpemtYu32-hW1I6Zr1LV8_CG3bFRZJJaobunSWnyM
        - https://mega.nz/file/LgI0UJoK#6tEkfI3brLUv45hDo0Puwhb-yrHpLDzXWOVQJm3j_Nw
        - https://mega.nz/file/KpAWWJaS#_m6ezlwFh1YRE69A2RF9VDIbjjF9ty2F4pl1Zd0M3z4
        - https://mega.nz/file/DtQ0HTSA#bp3HnCNh-YCMIVMHoQmj7DFNNSfLdBlG_z9846lZV0M
        - https://mega.nz/file/CxZGibxB#L9okKqxwCVo7FGInc-mJh5EBbAoFKf9HnCAPsG0spbA
        - https://mega.nz/file/X0ACmBwb#st2gRnKzKd2bx4wPZ8yg8vGY7t0LLf-jsWxiAqxeD5Q
        - https://mega.nz/file/ngZA3ZzK#Jl9AN0WXw2XdxlGxClNt7PfqU0OHoehpWYtREo1dPrs
        - https://mega.nz/file/S5QQBTjS#XIAUSGOf0_GzxcwjgBQLN7Qvx9p8iwN34PQrmI_NMIw
        - https://mega.nz/file/TwI2jDrR#q5yRZulvdNoAT87dyJvEXum88WmXCyDDpjVRqAuCId0
        - https://mega.nz/file/v9Q0zZaa#BwA9g8T9AptgorrXK3UiIB0Ho6RvGSm21oO9eOFupis
        - https://mega.nz/file/hVFHTYKD#GgGQfnFoQ928Qr6U-fkQOQ2TBIc3hRH5WetzK7DvqHs
        - https://mega.nz/file/VuoVRKYb#4tJ0oInUU_9_Kp9Y3xF-iHtf0iV1ic3g5CXVGCf33d8
        - https://mega.nz/file/ZuxTTATD#OJ6ot-5--xvQtwpummd_1qMLnp6Ur6HfAyn36kZVjj8
        - https://mega.nz/file/IihRGQqI#xW-CL73wwancJRCAViHCxgM6WSs-bfC5nt3g78K15C0
        - https://mega.nz/file/c34nwYTS#M3BLWc3VEyk6i64c0EFAyHuSCRhFtgMibbXVrTZZRxA
        - https://mega.nz/file/Ok9WAKqD#51ydhl7MlzimxxVs6sGhD83G9jKHpK0kFBdKHbiK1GA
        - https://mega.nz/file/jllkBCaa#USOfwP4XU6na23vofnBMXVERlDRVYvEis2nm2wDAz58
        - https://mega.nz/file/8BEQkRTJ#qYSLRCcReW9ULW7lDXnwdBj8HQkU8Q5xFX5ra9vXGSQ
        - https://mega.nz/folder/zlokjKpZ#jufaJUjnJb0lr7GhegYusg
        - https://mega.nz/folder/P1IyGLaJ#KiI5nvWasHWzkjH_0S7HEw
        - https://mega.nz/folder/ykw0zCzS#w4unlHx-4W_h1BigqjD9ug
        - https://mega.nz/folder/mtoUESYa#GMBvaYhpSt8-2Z1yI3sKNA
        - https://mega.nz/folder/6ox2SawC#_QhRSFZT16XMY3g_nasGCw
        - https://mega.nz/folder/LlJCiJYZ#Grbgk8i0ZIepW8F8dsaxbg
        - https://mega.nz/file/3h0zHCIQ#jddRRrLcr5rCVmJDXED-vGZltg2DjpgYREsP1wE8fBA
        - https://mega.nz/folder/q4hECCgZ#87SMqPYHfNrTksK_BjVOnA
        - https://mega.nz/folder/TkAyBRwK#1e7droggVg785-_2Cse2zg
        - https://mega.nz/folder/DkAAWZyI#Z2ce72r-PXjk4n-54OfQPg
        - https://mega.nz/folder/ypJQgLrY#9EtkY_Qo3lRahrdsTgA44A
        - https://mega.nz/folder/CsB2VR7K#r8D1Xj3CaKVYwjDxztQsow
        - https://mega.nz/folder/fopywaaS#bLJCL47OhamOKywrQ6w53w
        - https://mega.nz/file/f8sUnQTY#qMQMhn9F0KRQDdqnE4NnMiELOBaD0dza9394CYIbDXw
        - https://mega.nz/file/3llEDYba#jyP54RNHnLvjpHJHKVtV5jqFszd9qZsEYPvTFCVuZuQ
        - https://mega.nz/file/TktWiYQA#XunWZwrX1JWpWMN09b4eAzaKXwOmXTGgR340x6sLXy8
        - https://mega.nz/file/i81UBSCA#A5JnnAv3nXTlqUaYk7mODd4StM49t9fdZx5U_O3KNYY
        - https://mega.nz/file/vk1kRaYQ#peKNZXXLM3buY73zrmPZmg_h9ESjmjIEU1QBLtEoekg
        - https://mega.nz/file/Xss2UYYY#t1Y-wM3QPlAw8Xb2IonQyZI8g9e2bQFEwVlUNDU-GzU
        - https://mega.nz/file/3llQUYLI#_n1ttgSauPnjWHkhmeihA9PAyHfXrFyS78n4baBUImA
        - https://mega.nz/file/i89iECCR#LaN_ADDBD3n0SxMqkQUjSzuVfUNPp2Vg07J6IHWQzzg
        - https://mega.nz/file/b8hABL7b#uANgJOgQV3EI56fiFkjJQFmDrkRaZxNS70C3tTwaOJ4
        - https://mega.nz/file/zs5CWToB#GNCtlMDdN3jzvs0Odf_t8j-CV7HgMm_Kuh47MFU1Hdg
        - https://mega.nz/file/GloyCSzC#vfXwoLeVJ9A2KFZM0bVgNSxBGd6RAq1zZ01E_lNbfTA
        - https://mega.nz/file/6lhE1QqA#y8FtL04ozyqxSy_BKI9uyQ1hB4xWMLMqkxRO4xoyDhQ
        - https://mega.nz/file/alpElKQB#mOz3qyMDqVcTDAd90UIKsStqGv7C43GPYoL0qYFaPoc
        - https://mega.nz/file/3xpUzRiK#0z_lGroL8uOa59qM2ii4ze0361Tx5p4LGxxPnsJ05dE
        - https://mega.nz/file/Gg501BRA#KoD8tc2LsMik8o67MhqIvX33Q51FEWWKuU5EBOYPEOs
        - https://mega.nz/file/S14GhRaY#qIrfcR1rjDSuEauC6uPNvBhzwDPXnNSxBKbffYWSuj4
        - https://mega.nz/file/H8YACLzT#3PHMhpFXrUeGqsMi8mOivaUyY4nc2eIsOqOVRDUa7fo
        - https://mega.nz/file/K4gCRBwQ#U5Q9pZVWaZgGTPSByymZYSaJFyEgKi1aDm-DjDX5N7k
        - https://mega.nz/file/Hhp3kSLJ#kkNYuXKcJy3bLb9U0_mS8z1xHpPrHXFUmTMkPY-eK9Q
        - https://mega.nz/file/tcA02Z5b#4cq_hZHCXjZU23O6RjH61Lg-OQwO4eolHKApMDsZp8c
        - https://mega.nz/file/lRZiiTJC#8zbdW0WywxoVog-x655LYDcBQyyHvXgFB8BVo7xfPTQ
        - https://mega.nz/file/QFZQQBCb#0mThPuUcodSjelXnPVPXhYsB5ZBfn_o95vqAqvLsQhI
        - https://mega.nz/file/QZYkjR4I#QjvE2-t09ZnJs2oxpda1uidZPRTYYtAqhqbNvzYKEB0
        - https://mega.nz/file/QAQQibCa#jiwomgOuCIJPG_31UPcFAC9YuAALnobeYUa4wiEnMhc
        - https://mega.nz/file/gAQA0RxT#FPHknCHHQZ6F77AWlHmypIahIm4Ko_DvedtsnoOND-I
        - https://mega.nz/file/yR4VFSBS#ymbYJa5fieiJLsfoJAk4fb0u1WCMfposev-ScUAPNMA
        - https://mega.nz/file/eRhl1AaK#_IBJQJ4P_b1lSVTH4SzRYkaE3BhV1HNnmHdGSR08jl4
        - https://mega.nz/file/zVh3jAQA#kmEgs7pgDR97fMx31tyoqlNoj1bFn8qZCKigEMqUYFY
        - https://mega.nz/file/310jhCRY#H5YTAU29YSWWE5pVt9OcqPL8B1lsd42kDvtMSgBqSv4
        - https://mega.nz/file/eIg3wQoZ#HRJyIlGe1i_lVf7STkgV-WL-Tq7fTPtoL9Q2dvPwnzU
        - https://mega.nz/file/GFpzyCaL#OfYbM7HA4Q7wl-vRgJZMqOHQKZCmWxw8CoUe1JeB_Dk
        - https://mega.nz/file/qV5liCjS#B3RhcELAii5gqguevvSdMiESOKm8aS8XZQPhVHFQPlo
        - https://mega.nz/file/qJ5knZDQ#RAFEcgHoVLuz_Z2tkVU4nK3Z_CoGWROqbJljCGzHWZU
        - https://mega.nz/file/OssngY7Y#LsdO_M7pBSVLqlv5MHp5xlGANYhGjDWI817baw9iEjw
        - https://mega.nz/file/j50AhYSb#BRe52NudkWyn4R4GBvJWyNd-PpnaumHYBeeUyQPAt90
        - https://mega.nz/file/fxsixAIC#aQoEKd_46Wti1_3C9X5_IRuJvxFpEs_w4SwsjrTY8es
        - https://mega.nz/file/Nt4xSaTL#l3I2CQKDe5CVoCWrw8BwaNSAJCsvk_Kau4NDaZOTqZE
        - https://mega.nz/file/RppjECII#8Nx8VoFEh8BEmjMr04UEkl0XE3waZjY7Hucxci3PYKE
        - https://mega.nz/file/dpgnXQhA#j1b1ac7D54Z1ZyTE_Vee0Fq8b-mhByc2maZNMtjNvmE
        - https://mega.nz/file/Yc1A2YID#0hWpxScJ105s-WYuzCdM05zJbvbm3w-m9ne78ALciuw
        - https://mega.nz/file/8U9jUIKY#8On072jhy5wSwZ6MXg6evzzxYaqTHzRaY0yKgDl42_s
        - https://mega.nz/file/JB0lUaYR#2d5vGjUeGmFBurOv7v70PMU-_iOa4ZV6rmNlOo0xOuc
        - https://mega.nz/file/5QknmIZS#-O2gwRE3AtK3fHKNWfHLGsfCrYQ-7rwNnTll5BZXSxI
        - https://mega.nz/file/addn3I7K#SLB8o--kXwzBITEKsFuVCnoYTLqE3GLqtzLcxpu6tH0
        - https://mega.nz/file/PFdjhIBC#T3DvbSGQDUYQT6fI5Fsnkf361Lv_GyQDs28vsPXVGS0
        - https://mega.nz/file/EcEVzQoB#YBk31zePWLBbVNh_7m9b43SbpF50i9A1tFpt_XFle6g
        - https://mega.nz/file/focTnKJC#AVXlnT2wzS7vcO2P-Ru-b60hC-zv1z3nbZI1azx5Wbg
        - https://mega.nz/file/3IpljaIQ#Hdcrke8xXmlMbgY7VCGqD0NhggkmEn5CYAylCEX6oiY
        - https://mega.nz/file/mZQy3RLK#i9LNUrQqEoNnz19Iy1Jn-m45WH1n0sExcL5WEUEyQdI
        - https://mega.nz/file/nMQGlJjb#0YhSyI6U0F20lXlEh4FN0PItytWE1gGa-XKwITCk7_0
        - https://mega.nz/file/GAJGBThQ#BNThDbB6iTHMxVfvDax8RU9YII5GK1es4ikNctDCIjA
        - https://mega.nz/file/WIZzUC5Z#XL011KpUg_W40h1mLuNLh3nRxoIMhTKbFpFnt58QQLM
        - https://mega.nz/file/NA8QUKjA#5FExPUeZ1WmzqkMxXGwOjiGHzncKPGJTpopYc0Vl0Cc
        - https://mega.nz/file/oU12hABD#-sy6qivhZweNbct-aowYjGxXpPQsO9h72Q8MzazEVmk
        - https://mega.nz/file/IM9UUZoZ#bEMR4D-x4KUtY6dI989w7AWvwHsiYrP4npwEf8C4-QY
        - https://mega.nz/file/8Q8USbLC#ldcFcdBfywl_qV0juWfCa29I6gdD20cxDvVPSzUCCA0
        - https://mega.nz/file/8FsQHZKT#wIS4uoGmj1SylkshZJ-IFPKvAIbPj96mWibTaGxDLkA
        - https://mega.nz/file/pZ90gIrB#SHsIBLt2AYpls3_42kzfzL6_nK578zwLc8WKvqg_Dr8
        - https://mega.nz/file/Hktk3C5I#ieGims4eEuGz5fkPXelXJCV1mIBxW9oVOCqUMlT4nfs
        - https://mega.nz/file/O89QELZT#kCSY1rmcVn9UA5Np2zWGouL8pfYLxs-wfG6b2dFp3zQ
        - https://mega.nz/file/ig0jCSAR#lFs6g1CN9qHTsRrfOcf0Z4x8WsTBnB68Q4pUIYupT40
        - https://mega.nz/file/St0iFLAR#Z-uEFMesYzwuWMpnnYzMVeBMdsbWiHPcz1x3XLI6t_c
        - https://mega.nz/file/fk1mSZTL#GH2YIj6g3UOllzuNBeCicqytQWLQExWhROAj5bNHbYA
        - https://mega.nz/file/v91zVIpA#4byrHw55WxJjZ3IDCRY5eKSe_0_7JSXea9NGqqpAmqs
        - https://mega.nz/file/7k82UDyJ#wUMXtKTzQPVxIjbsTXtWEEiuOMRLTAYm3zucKTFV-3o
        - https://mega.nz/file/Kix10AKQ#a9AbQdbAFpUlS9fYWDkczryqhJfciRlCGfW5Xx4HAS0
        - https://mega.nz/file/njwzTQRb#jjSEqFn8KMZDIilvPU25CjfD0avW4Q7GMsYR6_FVKKg
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
      id: cache
      with:
        path: megatools-1.11.0-git-20200830-linux-x86_64
        key: megatools-1.11.0-git-20200830-linux-x86_64
    - name: Mega
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl -OL https://megatools.megous.com/builds/experimental/megatools-1.11.0-git-20200830-linux-x86_64.tar.gz
        tar xvf *.gz
    - name: Leech
      run: |
        mkdir leech
        megatools*/megatools dl --path leech/ ${{ matrix.url }}
        cd leech
        find . -size +2G -exec split -b 1G --numeric-suffixes=1 {} {}.0 \;
        find . -size +2G -exec rm {} \;
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: leech/*
        tag: latest
        overwrite: true
        file_glob: true
