name: leech

on:
  push:
    paths:
    - '.github/workflows/leech.yml'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        url:
        - https://mega.nz/folder/KEskEbjL#UkjpieqDbr6uZpnkPtHHBg/file/mE1WVCII
        - https://mega.nz/folder/KEskEbjL#UkjpieqDbr6uZpnkPtHHBg/file/KNlmSDbI
        - https://mega.nz/folder/KEskEbjL#UkjpieqDbr6uZpnkPtHHBg/file/mR1CzLqZ
        - https://mega.nz/file/yRkhBSqA#iyFHFjNI7G3FNhvl5WCTWJT7Wd9RYqhfWsA52BnlZh4
        - https://mega.nz/file/dxwEhKSD#pFE_1vrZGkC4kMGLIqWJ48VqeRG2H8cAYFfoMMpD0rM
        - https://mega.nz/folder/w0NnzaoT#i0kZOqbdgGxXYbAvLCfM0Q
        - https://mega.nz/folder/SZVCnbjQ#0etbUuFWz-Y7mbvI4uQ_Sg/file/XYUWwbiD
        - https://mega.nz/folder/SZVCnbjQ#0etbUuFWz-Y7mbvI4uQ_Sg/file/SJdi1DZY
        - https://mega.nz/folder/SZVCnbjQ#0etbUuFWz-Y7mbvI4uQ_Sg/file/bdMWATKD
        - https://mega.nz/folder/SZVCnbjQ#0etbUuFWz-Y7mbvI4uQ_Sg/file/jcMUXDqB
        - https://mega.nz/folder/SZVCnbjQ#0etbUuFWz-Y7mbvI4uQ_Sg/file/eJUUkJZR
        - https://mega.nz/file/ckgm2aYB#TIlfBgXMECFQUxJMNajoi-au8k2pqFXhsmcmMR5Gy_o
        - https://mega.nz/file/Kmhhwa5Y#-cu7SIaGGN5udsGY36Ao4EUKVH2ITaW2rql6bvy5q2Y
        - https://mega.nz/file/OYsACYzJ#Potnt-zJX4WUT-6OtUKKBhRJgUrdukRigFCjcjdz4Pc
        - https://mega.nz/file/qFlgXabS#VYoZZOEhXBbzjd5a2utdZdI139ZK1yvHo415sbciezM
        - https://mega.nz/file/GQ9zyAiT#KtjayrwkeLSDGUTygiZt9LgLgqVNq_D8_S3BRpy18QE
        - https://mega.nz/file/Tqo0TTAR#DzK7Iyld2eJ4f7PUDK2jAGMgKoXGniku1dGQg5SVSTs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
      id: cache
      with:
        path: megatools-1.11.0-git-20210505-linux-x86_64
        key: megatools-1.11.0-git-20210505-linux-x86_64
    - name: Mega
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl -OL https://megatools.megous.com/builds/experimental/megatools-1.11.0-git-20210505-linux-x86_64.tar.gz
        tar xvf *.gz
    - name: Leech
      run: |
        mkdir leech
        megatools*/megatools dl --path leech/ ${{ matrix.url }}
        cd leech
        find . -size +2G -exec split -b 1G --numeric-suffixes=1 {} {}.0 \;
        find . -size +2G -exec rm {} \;
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: leech/*
        tag: latest
        overwrite: true
        file_glob: true
