name: leech

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        url:
        - https://mega.nz/folder/8ctC3YhZ#7gvSD-XYq-rdB1uFfldDzA
        - https://mega.nz/file/pR0WkBiR#qcnqgtxx2X_2J97qwNWPR-8lUJFVJx_hTs8aTjyym7s
        - https://mega.nz/file/4GQ2RDzD#K3c0Wnq2Q98gSVM9ZvPYuyX1SswJCf7tTwHjOy6IpcU
        - https://mega.nz/file/2zwDwCTR#Q9AgXfkJehB3Jca29Eox0Wkp3qhDs7Ne2mR_FI_90lY
        - https://mega.nz/folder/EhxixQ4Q#HncTjHldT-3uyeBKCtl-Vw
        - https://mega.nz/file/A1pGBRBC#E90Fln_XbQ-1E1HrADGmrFyIIISTChz1_YMUIC0NP78
        - https://mega.nz/folder/lto0GKxC#tI0qdFuETo8TxoQYQC08Nw
        - https://mega.nz/folder/w9YRkQaI#5XEBdGmnHTPauq_dpq1a4w
        - https://mega.nz/folder/0AlUUSSZ#5Uk8SsFAN87nxr2HUGJ6mg
        - https://mega.nz/folder/pNNAWRhR#yT0DLRGi1ziMXpvTu5GgmA
        - https://mega.nz/folder/wEsCDSaZ#p-mNwAinMhL_ARwE9wNZWA
        - https://mega.nz/folder/fKAF3aKL#ccjv4aY0eHeMmBDqe1CIrg
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
      id: cache
      with:
        path: megatools-1.11.0-git-20210505-linux-x86_64
        key: megatools-1.11.0-git-20210505-linux-x86_64
    - name: Mega
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl -OL https://megatools.megous.com/builds/experimental/megatools-1.11.0-git-20210505-linux-x86_64.tar.gz
        tar xvf *.gz
    - name: Leech
      run: |
        mkdir leech
        megatools*/megatools dl --path leech/ ${{ matrix.url }}
        cd leech
        find . -size +2G -exec split -b 1G --numeric-suffixes=1 {} {}.0 \;
        find . -size +2G -exec rm {} \;
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: leech/*
        tag: latest
        overwrite: true
        file_glob: true
