name: leech

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        url:
        - https://mega.nz/file/UM1imRSa#k5VaSG4ZUutQ2T87XFC70S6DX0qG5qHbqF_0rrnAQSs
        - https://mega.nz/file/NRlk2bqB#UnCUH87cGawUisuAvw4qYBKlbfFXqYa40b0JJEZ0rlg
        - https://mega.nz/file/9VMQlbDa#zBXKdVqL42sa7F7QWZATL1GvHkO9fT7DoFiuB6P1qvU
        - https://mega.nz/file/xrhhEKiI#jgd4E6UzLOHa0e8DpG29w7M3OihKgI1IL77WJFi_doQ
        - https://mega.nz/file/8ih3mAob#FywBuJw7KHoD5iaOOSxYeTyu4aDDsIoBH-ThXnXZ3V0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
      id: cache
      with:
        path: megatools-1.11.0-git-20200830-linux-x86_64
        key: megatools-1.11.0-git-20200830-linux-x86_64
    - name: Mega
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl -OL https://megatools.megous.com/builds/experimental/megatools-1.11.0-git-20200830-linux-x86_64.tar.gz
        tar xvf *.gz
    - name: Leech
      run: |
        mkdir leech
        megatools*/megatools dl --path leech/ ${{ matrix.url }}
        cd leech
        find . -size +2G -exec split -b 1G --numeric-suffixes=1 {} {}.0 \;
        find . -size +2G -exec rm {} \;
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: leech/*
        tag: latest
        overwrite: true
        file_glob: true
