name: leech

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        url:
        - https://mega.nz/file/Txg02Qga#b3mhwLMnInopR051UFC4TLRZTYVJQYB_3jQB3N_uTdg
        - https://mega.nz/file/7pY2HJRT#stahAi-oAyPudUOTH479QCKw3oN3Rnjjc-y9NmzDhqM
        - https://mega.nz/file/SgI2mThT#JOqrH1ca9tN9J6Z1Fbo_81WWpn8r7-50z0KoMONunMs
        - https://mega.nz/file/KhAWRDgR#CgXS-WTgP9d7gyyNBn8Eh0m6O8O8Eqi4Z4ng3Vdd11M
        - https://mega.nz/file/WoRGETQD#Fg_uazxUH0yW9w-Orn_SbQIc2ONT0BCBkwXDloM2_UE
        - https://mega.nz/file/29YEBBwQ#Slm6ieYhGbLBih-8RzECjT-x_cSR9-aS4IO1tPPr1LU
        - https://mega.nz/file/20ISzTRC#SLfHE_6hPR4eDFHp2B-psAGo7QeIEVpPJmbRO9W1oTA
        - https://mega.nz/file/fsB0SRAZ#NQCZfiFl4KCxs5kzRvlaLMxjDkNTcDaneKhktVtTxpE
        - https://mega.nz/file/aoJA0ToT#_GcvOhVM_ufgWAEY939-Pv5xu5QmsqeLKUiwZ0M3sr4
        - https://mega.nz/file/y1BGiDiL#LiufwjvR9iULic_1J6hyQwGX2RNOJc-2WToStZWdiS0
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
      id: cache
      with:
        path: megatools-1.11.0-git-20200830-linux-x86_64
        key: megatools-1.11.0-git-20200830-linux-x86_64
    - name: Mega
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl -OL https://megatools.megous.com/builds/experimental/megatools-1.11.0-git-20200830-linux-x86_64.tar.gz
        tar xvf *.gz
    - name: Leech
      run: |
        mkdir leech
        megatools*/megatools dl --path leech/ ${{ matrix.url }}
        cd leech
        find . -size +2G -exec split -b 1G --numeric-suffixes=1 {} {}.0 \;
        find . -size +2G -exec rm {} \;
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: leech/*
        tag: latest
        overwrite: true
        file_glob: true
