name: nvchecker

on:
  workflow_dispatch:
  schedule:
  - cron: '5 0 * * *'
  push:
    paths:
    - 'xxoo.toml'

jobs:
  version_check:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.AUTO }}
    - name: Check Latest Version
      run: |
        pip install pycurl tornado nvchecker in_place
        nvchecker -c xxoo.toml
        nvcmp -c xxoo.toml > cmp
        if [ -s cmp ]
        then
          git config --global user.name 'eko5624'
          git config --global user.email 'datong5624@gmail.com'
          mv new.json old.json
          git add old.json
          git commit -m "Automate"
          git push
        fi
