name: nvchecker

on:
  workflow_dispatch:
  schedule:
  - cron: '1 1 * * *'
  push:
    paths:
    - 'xxoo.toml'
    - 'old.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Version Check
      run: |
        sudo apt install python3-pycurl python3-tornado
        pip3 install nvchecker
        nvchecker -c xxoo.toml
        nvcmp -c xxoo.toml > cmp
        if [ -s cmp ]
        then
          mv new.json old.json
          git add old.json
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -am "Automated report"
          git push
        fi
