name: nvchecker

on:
  workflow_dispatch:
  #schedule:
  #- cron: '0 0 * * *'
  push:
    paths:
    - 'xxoo.toml'

jobs:
  version_check:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@main
      with:
        token: ${{ secrets.AUTO }}
    - name: Check Latest Version
      run: |
        #sudo apt install python3-pycurl python3-tornado
        pip3 install pycurl tornado in-place nvchecker
        nvchecker -c xxoo.toml
        nvcmp -c xxoo.toml > cmp
        if [ -s cmp ]
        then
          git config --global user.name 'eko5624'
          git config --global user.email 'datong5624@gmail.com'
          mv new.json old.json
          git add old.json
          git commit -m "Automate"
          git push
        fi
