name: nvchecker

on:
  workflow_dispatch:
  #schedule:
  #- cron: '0 0 * * *'

jobs:
  version_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        token: ${{ secrets.AUTO }}

    - name: Set environment variables
      run: |
        sed -i -e "s/__GITHUB_ACCESS_TOKEN__/${{ secrets.AUTO }}/g" keyfile.toml     
        
    - name: Check Latest Version
      run: |
        sudo apt install python3-pycurl python3-tornado
        pip3 install in_place nvchecker
        nvchecker -c xxoo.toml -k keyfile.toml
        nvcmp -c xxoo.toml > cmp
        if [ -s cmp ]
        then
          git config --global user.name 'eko5624'
          git config --global user.email 'datong5624@gmail.com'
          mv new.json old.json
          git add old.json
          git commit -m "Automate"
          git push
        fi
